const CreditConstants = {
    "Anders Damkjær Nielsen": "",
    "Alexandru Busnita": "https://www.linkedin.com/in/alexandrubusnita/",
    "Amanda Maria Stockholm James": "https://www.mastokja.com/",
    "Andreas Saur Feldstedt": "https://www.linkedin.com/in/andreas-feldstedt-947225179/",
    "Astrid Knappmann": "https://astrinaar.com/",
    "Brian Kale": "https://twitter.com/brianwkale",
    "Balder Herman Brusch": "https://www.linkedin.com/in/balder-br%C3%BCsch/",
    "Christoffer Alexander Krakou": "http://krakou.dk",
    "Dom Ford": "https://www.researchgate.net/profile/Dom_Ford",
    "Francesco Rugerfred Sedda": "http://rugerfred.com",
    "Ida Broni Christensen": "http://idabroni.com/",
    "Joe Osborne": "http://joes.games/",
    "Julian Abela": "",
    "Lorena Ciobanu": "https://www.facebook.com/lorena.ciobanu.1",
    "Malte Mulbjerg Rothgardt": "",
    "Marie-Louise Alexius Sørensen": "https://www.linkedin.com/in/marie-louise-s%C3%B8rensen-6b0236128/",
    "Mateo Perez": "https://twitter.com/faketortilla",
    "Mathias Jean Johansen": "",
    "Mathias Stie-Svendsen": "",
    "Mathies Wiencke": "",
    "Morten Mansdal Larsen": "",
    "Nathan Cranford": "https://twitter.com/etuden88",
    "Ole Gunnar Stensrud": "https://www.artstation.com/f4celess",
    "Rareş Popa": "https://poparares.wordpress.com",
    "Sarah Grossi": "https://itsarahstuff.com/portfolio/",
    "Stephen Whyte": "https://twitter.com/stevewhytemusic",
};

export default CreditConstants;